[server]
maxUploadSize = 5000
maxMessageSize = 5000
enableCORS = false
enableXsrfProtection = true
runOnSave = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1E3A8A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F4F6"
textColor = "#111827"
font = "sans serif"
